spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  jwt:
    secret: ${JWT_KEY}
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

# s3
amazon:
  aws:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: ${S3_BUCKET_NAME}

voice_analysis_server: ${ANALYSIS_SERVER_URL}
